# Generated by Django 5.1.5 on 2025-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_tasks_userid_tasks_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subtask',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
